### ISSUE TITLE
Feature: shortcuts and extracting alt text from file types

### ISSUE THREAD

**Issue by HanBoyou** [grainger-illinois/CTCast#19]
My current understanding to this function is that we could extract from the input message "shortcuts" that is replaced automatically by the alt text of some picture (by page/index)
**Task breakdowns:**
- [x] parse text input as command 
    - [ ] add visual notification that shows which text input are converted.
    - [ ] add guesses based on partial shortcut
- [x] display shortcuts in shortcut component
    - [ ] beautify popup of  long text
    - [ ] add editablity to shortcut and long text
- [x] upload files
-------------------------------
- [x] extract alt text from document,  <del>add interface that displays alt text from document</del>
    - [x] docx
    - [ ] pdf
    - [x] pptx
- [x] parse alt text as map
    - [x] docx
    - [ ] pdf
    - [x] pptx
- [x] store shortcut map in local storage.
    - [ ] store shortcut map in config file similar to logs.
  ---------------------------
**Bug:**
- [ ] Select file => Confirm => Select file => Press Esc => Fail

**Comment by HanBoyou** [comment]
Finished most functions of alt-text extracting from files.
For example
![image](https://user-images.githubusercontent.com/55033157/198900624-7cf5adf5-fd43-4a8a-bbcb-44f0096b303d.png)
Will result in
![image](https://user-images.githubusercontent.com/55033157/198900652-df4f7344-653e-4001-b34f-459ce5e35141.png)
